project:
  type: website
  output-dir: _site

website:
  title: "Spencer Bark"
  favicon: images/favicon.png
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: problems.qmd
        text: Problems Iâ€™m Exploring
      - text: Projects
        menu:
          - href: projects/project-1.qmd
            text: AI PM Todo App

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="icon" type="image/png" href="/portfolio/images/14d03ae8-1e50-46d1-9f40-3bc07aa309f5.png">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

